<template>
    <div>
        <p class="mb-4">These Terms of Service (“Terms”) are provided on behalf of ({{ app_name }}) (“We,” or “Site,” or "Website"). Please carefully review these Terms each time you use the site and if you do not agree to these Terms, you are not authorized to access or use the website and you shall not access or otherwise use the website. We reserve the right to modify these Terms at any time and for any reason in our sole discretion without notice to you except posting on these Terms and your continued use of the site thereafter constitutes your acknowledgement and consent to any and all modifications.</p>
        <p class="mb-1"><b>WEBSITE’S SERVICES.</b></p>
        <p class="mb-4">The operators of this website offer a free infomediary service that passes the information you affirmatively provide to Lenders, advertisers, networks, and other financial service providers who may secure a loan, financial product, or service for you. When you submit a loan request on our site, we will pass your information to Lenders who may offer you a short-term loan. Although always varying, the typical short-term loans offered by lenders which you may connect with on this site are intended to provide temporary financing to resolve immediate financial needs and should not be considered long-term solutions. Providing your information on this site does not guarantee that you will be connected with a Lender or financial service provider or approved for a loan for a specific amount and we make no guarantees. The operators of this website are not an agents, brokers, or representatives for any Lender or financial service provider and therefore, we do not endorse, recommend, or warrant service or loan product and do not control the rates and fees that third-parties may charge. We highly encourage you to carefully review all terms, conditions, and repayment schedules of any loan offer issued to you by a Lender prior to accepting or declining a loan and understand that you are never obligated to accept an offer from a Lender. You may end your participation at any time during the process and are never obligated to accept a loan. Since we are not a lender or make credit decisions, this site has no accountability or knowledge of any loan terms and details you may be presented or agree to with Lenders you may connect with on this site. For information about loan specifics, contact your Lender directly. This site receives compensation from the Lenders and financial service providers whose products appear on the site or whose products may be offered to you in the form of a payment for each consumer request (“referral”) we pass to them. This compensation may impact what offers you receive from Lenders and how or where products appear on this site. This site does not include all Lenders available in the marketplace and you are encouraged to conduct due diligence prior to acceptance of any short-term loan.</p>
        <p class="mb-4">It is important to for you to consider that in some cases, you may be given the option of securing a loan from a Tribal Lender. Lenders that are an extension of a federally recognized Indian Tribe are owned by independent sovereign nations and in many instances may not be required to follow local or state laws regarding finances, rates, fees and other loan terms. If you are connected to a Tribal Lender, please understand that the Tribal Lender’s rates and fees or loan terms may be higher than state-licensed lenders. Additionally, Tribal Lenders may require you to agree to resolve any disputes in a tribal jurisdiction which may affect your statutory rights. </p>
        <p class="mb-1"><b>SHARING INFORMATION WITH LENDERS AND FINANCIAL SERVICE PROVIDERS.</b></p>
        <p class="mb-4">When You submit a loan request on this site, you acknowledge and agree that we are passing (or “sharing”) your information to Lenders and Financial Service Providers within our network in order to connect you with the services and goods you are requesting. These third-party Lenders and Financial Service Providers may store and access this information to process your loan request and potentially offer you a loan. By providing your information and allowing us to share that information, you are expressly requesting to be contacted by our site and lenders and financial service providers in our network via electronic mail (e-mail), telephone (phone call or text), and/or direct mail to assist with your loan request or present you additional related offers which may be of interest. Since we are not Lenders, after passing your information our services for you end. </p>
        <p class="mb-1"><b>CONSENT FOR LENDERS TO VERIFY INFORMATION AND OBTAIN CREDIT SCORES AND REPORTS.</b></p>
        <p class="mb-4">This site is not a lender nor do we perform credit checks or secure credit reports since we do not make credit decisions or offer loans. However, the Lenders who receive the information you affirmatively provide on this site may use your information to verify consumer identity and perform credit checks which may impact your credit score. Lenders in our network may perform a credit checks or secure your credit score before making their decision to offer you a loan by using the three major reporting bureaus like, TransUnion, Experian and Equifax, as well as other alternate sources of consumer information.  By submitting your loan request on this site, you are providing express written consent and authorization under the Fair Credit Reporting Act to allow such Lenders and third-parties to use your information in this manner (to obtain credit reports, credit scores, or other information from any consumer reporting agency) It is important to remember that non-payment of loans may impact your credit score negatively if your credit provider chooses to report delinquencies.</p>
        <p class="mb-1"><b>CONSENT TO RECEIVE ELECTRONIC MAIL, TELEPHONE CALLS, AND SMS COMMUNICATIONS.</b></p>
        <p class="mb-4">By submitting a loan request through this site, You are providing express written consent to be contacted by this website, Integrated Delivery Solutions (SMS Code #21347), Third-party Lenders and financial service providers, and marketing partners who we pass your information to, by: (1) Telephone, at the number you have provided, whether landline or cellular, even if your telephone phone number is on any Federal or State “Do Not Call” list at the time of submission; You also expressly consent and agree pursuant to the Telephone Consumer Protection Act (“TCPA”) to receive pre-recorded calls, ringless voicemail messages, and/or calls made with an automatic dialing system; (2) Electronic Email (e-mail) at the email address you provide; and (3) SMS messaging to the mobile phone number that you provide, in which case data and messaging rates may apply. Your consent to receive marketing telephone calls and SMS is not required to use the site’s services.</p>

        <p class="mb-1"><b>LINKS TO THIRD PARTY WEBSITES.</b></p>
        <p class="mb-4">The operators of this site are not responsible for the information practices employed and privacy practices maintained by websites linked to or from our site. Generally, links to third-party websites will have information, privacy, and security practices which differ substantially from our site and therefore you are advised to thoroughly review the privacy policies and terms of services of these sites prior to providing any of your information. The existence of such links to third-party websites should in no circumstance be considered an endorsement or recommendation of those websites or any services offered through those websites. </p>

        <p class="mb-1"><b>INTELLECTUAL PROPERTY RIGHTS, COPYRIGHTS, AND TRADEMARKS.</b></p>
        <p class="mb-4">All software, design, text, information, content, data, databases, images, photographs, illustrations, audio and video clips, artwork, graphic material, or other copyrightable elements (collectively, “Content”) are the property our site and/or our subsidiaries, affiliates, assigns, licensors, vendors, partners, or other respective owners and are fully protected, without limitation, pursuant to copyright laws. No Content on this site may be reproduced, modified, used to create derivative works, displayed, performed, published, distributed, disseminated, broadcast, or circulated without our express prior written consent of this site. (WEBSITE) and all it’s related logos (collectively, “the Trademarks”) constitute our trademarks and service marks. Other company, product, and service names and logos used and displayed on this site may be trademarks or service marks owned other third-parties. You may not use, copy, display, distribute, modify, or reproduce any of the trademarks found on this site without our express prior written consent. Any unauthorized use of content or trademarks constitutes a breach of these Terms. The use of any of the Trademarks as part of a link to or from any site is prohibited unless advance written approval is provided by our site. All right, title and interest in and to the Website, any content thereon, our Services, the technology related to our Services, and any and all technology and any content created or derived from any of the foregoing is our exclusive property and nothing on this site or these Terms is intended to provide any authorization or consent to its such use. </p>

        <p class="mb-1"><b>INDEMNITY</b></p>
        <p class="mb-4">You agree to indemnify, defend, and hold this site and its operators harmless from and against any and all third party actions, suits, claims and/or demands and any associated losses, expenses, damages, costs, and other liabilities (including reasonable attorneys’ fees), arising out of or relating to your request or submission of information, use or misuse of any aspect of the Services or Site, or your violation of these Terms. You are required to reasonably cooperate in the defense of any such claim or demand. We and any third party involved in creating, producing or delivering the Site or Services reserves the right, at our sole discretion, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, at your expense, and you will not in any event settle any such matter without our prior written consent and any such third party.</p>

        <p class="mb-1"><b>DISCLAIMER OF WARRANTIES.</b></p>
        <p class="mb-4">THIS SITE, OUR SERVICES, AND ALL ASPECTS PROVIDED ARE PROVIDED “AS IS” “WITH ALL FAULTS”, “AS AVAILABLE,” AND WITHOUT ANY REPRESENTATION OR WARRANTY, WHETHER IMPLIED OR STAUTORY. WE AND OUR OFFICERS, DIRECTORS, EMPLOYEES, AND THIRD PARTY AFFILIATES (COLLECTIVELY, THE “PARTIES”) DISCLAIM ANY AND ALL REPRESENTATIONS, WARRANTIES OR GUARANTEES OF ANY KIND, WHETHER EXPRESS, IMPLIED OR STATUTORY, TO THE SITE, SERVICES, ANY DOCUMENTATION PROVIDED OR MADE AVAILABLE TO YOU, AND ANY OTHER SERVICES AND RELATED MATERIALS AND SERVICES PROVIDED TO YOU BY ANY OF THE PARTIES, INCLUDING, BUT NOT LIMITED TO, ANY WARRANTIES: (1) AS TO TITLE, MERCHANTABILITY, FITNESS FOR ORDINARY PURPOSES, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, SYSTEM INTEGRATION, AND WORKMANLIKE EFFORT; (2) THE QUALITY, ACCURACY, TIMELINESS, OR COMPLETENESS OF THE SITE OR SERVICES OR ANY ASPECT THEREOF; (3) THOSE ARISING THROUGH COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE; (4) THE SITE OR SERVICES CONFORMING TO ANY FUNCTION, DEMONSTRATION OR PROMISE BY ANY PARTY; AND (5) THAT ACCESS TO OR USE OF THE SITE OR SERVICE WILL BE UNINTERRUPTED, ERROR-FREE OR COMPLETELY SECURE. ANY RELIANCE UPON THE SITE OR SERVICES IS AT YOUR OWN RISK AND THE PARTIES MAKE NO WARRANTIES. </p>

        <p class="mb-1"><b>LIMITATION OF LIABILITY.</b></p>
        <p class="mb-4">YOU ACKNOWLEDGE AND AGREE THAT ACCESSING AND USING THIS SITE AND ITS SERVICES IS AT YOUR OWN RISK. UNDER NO CIRCUMSTANCES WILL THIS SITE AND ITS OPERATORS BE HELD LIABLE FOR ANY DEFECTS, FAULTS, INTERRUPTIONS, OR DELAYS IN THE OPERATION OR TRANSMISSIONOF SERVICES, OR ANY INACCURACIES, ERRORS OR OMISSIONS IN THE INFORMATION CONTAINED IN THE SITE OR SERVICES. UNDER NO CIRCUMSTANCES WILL THIS SITE, AND ITS OWNERS, DIRECTORS, OFFICERS, OPERATORS, AND EMPLOYEES, BE HELD LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, PUNITIVE OR ANY OTHER DAMAGES, INCLUDING, BUT NOT LIMITED TO, LOST PROFITS, ARISING OUT OF, BASED ON, RESULTING FROM, OR IN CONNECTION WITH THE SITE OR SERVICES, THESE TERMS, OR YOUR USE OR INABILITY TO USE ANY OF THE FOREGOING, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ALL OF THESE LIMITATIONS APPLY REGARDLESS OF THE CAUSE OR FORM OF ACTION, WHETHER THE DAMAGES ARE CLAIMED UNDER THE TERMS OF A CONTRACT, TORT OR OTHERWISE, AND EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>

        <p class="mb-1"><b>PRIVACY PRACTICES.</b></p>
        <p class="mb-4">Our Privacy Policy is incorporated into, subject to, and made part of these Terms and can be viewed by clicking the following <span class="modal-link" v-if="modals" data-bs-toggle="modal" data-bs-target="#privacy"> Privacy Policy</span> <a v-else href="/privacy"> Privacy Policy</a></p>

        <p class="mb-1"><b>SEVERANCE.</b></p>
        <p class="mb-4">These Terms operate to the fullest extent permissible by law and if any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall be enforced to the fullest extent possible, and the remaining provisions of these Terms shall remain in full force and effect. The headings used in the Terms are intended for convenience only, and shall not affect the drafting or interpretation hereof or thereof.</p>

        <p class="mb-1"><b>NO WAIVER OF TERMS.</b></p>
        <p class="mb-4">Our failure to enforce any provision of these Terms shall in no way be construed as a waiver of such or any future provision.</p>

        <p class="mb-1"><b>CHOICE OF LAW.</b></p>
        <p class="mb-4">These Terms and their interpretation, performance, and enforcement shall be construed in accordance with the laws of the State of Nevada, except for any conflict or choice of law principle thereof that would lead to the application of another jurisdiction's laws to the rights and duties of the parties. You and this site intend for the laws of the State of Nevada to apply in any dispute or legal proceeding. Any claim you may have against the site must be brought within one (1) year after the cause of action arises, or such claim or cause of action is barred and waived. </p>

        <p class="mb-1"><b>CLASS ACTION WAIVER.</b></p>
        <p class="mb-4">TO THE EXTENT PERMISSIBLE BY LAW, YOU AND WE (COLLECTIVELY, THE “PARTIES”) AGREE TO WAIVE ANY RIGHT TO PURSUE DISPUTES OR LEGAL CLAIMS ON A CONSOLIDATED OR CLASS-WIDE BASIS; THAT IS, TO EITHER JOIN A CLAIM WITH THE CLAIM OF ANY OTHER PERSON OR ENTITY OR ASSERT A CLAIM IN A REPRESENTATIVE CAPACITY ON BEHALF OF ANYONE ELSE IN ANY LAWSUIT, ARBITRATION, OR OTHER PROCEEDING. YOU HEREBY ACKNOWLEDGE THAT BY AGREEING TO THIS CLASS ACTION WAIVER, YOU MAY ONLY BRING CLAIMS AGAINST THIS SITE IN AN INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS ACTION OR REPRESENTATIVE PROCEEDING.</p>

        <p class="mb-1"><b>ARBITRATION.</b></p>
        <p class="mb-4">YOU AND WE (COLLECTIVELY, THE "PARTIES") AGREE TO SUBMIT ANY DISPUTE OR LEGAL ACTION ARISING OUT OF OR IN ANY WAY RELATING TO THIS SITE TO BINDING ARBITRATION CONDUCTED BY A SINGLE ARBITRATOR UNDER THE COMMERCIAL RULES OF THE AMERICAN ARBITRATION ASSOCIATION ("AAA") IN LAS VEGAS, NEVADA, RATHER THAN A PROCEEDING IN A COURT OF LAW. ANY AND ALL DISCOVERY SHALL BE COMPLETED WITHIN ONE-HUNDRED AND TWENTY (120) CALENDAR DAYS FOLLOWING THE APPOINTMENT OF AN ARBITRATOR. THE PARTIES SHALL BE ENTITLED TO REPRESENTATION BY COUNSEL, TO APPEAR AND PRESENT WRITTEN AND ORAL EVIDENCE AND ARGUMENT AND TO CROSS-EXAMINE WITNESSES PRESENTED BY THE OTHER PARTY, PROVIDED THAT, WHERE APPROPRIATE, THE ARBITRATOR MAY RECEIVE TESTIMONY VIA TELEPHONE, VIDEO, OR OTHER ELECTRONIC MEDIUMS OF COMMUNICATION. THE ARBITRATION AWARD SHALL BE ISSUED IN WRITING AND THE ARBITRATOR SHALL PROVIDE WRITTEN REASONS AND JUSTIFICATIONS FOR THE AWARD. THE ARBITRATION SHALL BE BINDING, MEANING THAT THE AWARD OF THE ARBITRATOR SHALL BE FINAL AND BINDING ON THE PARTIES HERETO AND MAY BE ENFORCED IN ANY COURT OF COMPETENT JURISDICTION. THE PREVAILING PARTY IN ANY ARBITRATION PROCEEDING TO ENFORCE ITS RIGHTS HEREUNDER SHALL BE ENTITLED TO RECOVER REASONABLE ATTORNEYS' FEES AND OTHER REASONABLE COSTS, INCLUDING FEES OF THE ARBITRATOR AND THE AAA, INCURRED IN THE ACTION OR PROCEEDINGS, NOT TO EXCEED TWO-HUNDRED AND FIFTY THOUSAND DOLLARS ($250,000.00). IN NO EVENT SHALL THE ARBITER AWARD PUNITIVE OR EXEMPLARY DAMAGES. THE PARTIES SHALL WAIVE ANY RIGHT THEY MAY HAVE TO AN APPEAL OF THE ARBITRATOR'S DECISION AND/OR AWARD. EACH PARTY RETAINS THE RIGHT TO SEEK JUDICIAL ASSISTANCE: (A) TO COMPEL ARBITRATION, (B) TO OBTAIN INTERIM MEASURES OF PROTECTION PRIOR TO OR PENDING ARBITRATION, (C) TO SEEK INJUNCTIVE RELIEF IN THE COURTS OF ANY JURISDICTION AS MAY BE NECESSARY AND APPROPRIATE TO PROTECT THE UNAUTHORIZED DISCLOSURE OF ITS PROPRIETARY OR CONFIDENTIAL INFORMATION; (D) FOR ANY CLAIMS OF INFRINGEMENT OR MISAPPROPRIATION OF THIS SITE'S COPYRIGHT, TRADEMARK, OR TRADE SECRETS; AND (E) TO ENFORCE ANY DECISION OF THE ARBITRATOR, INCLUDING THE FINAL, BINDING AWARD. IF ANY AAA RULE CONFLICTS WITH THESE TERMS OR THIS SECTION, THESE TERMS AND THIS SECTION SHALL CONTROL. BY AGREEING TO BINDING ARBITRATION, YOU AGREE THAT THE PARTIES ARE EACH WAIVING THE RIGHT TO FILE A LAWSUIT AND THE RIGHT TO A TRIAL BY JURY IN ANY ACTION IN ANY WAY ARISING OUT OF OR RELATED TO THIS AGREEMENT. NOTWITHSTANDING ANYTHING TO THE CONTRARY, ANY PARTY TO THE ARBITRATION MAY AT ANY TIME SEEK INJUNCTIONS OR OTHER FORMS OF EQUITABLE RELIEF FROM ANY COURT OF COMPETENT JURISDICTION.</p>

        <p class="mb-1"><b>MODIFICATIONS TO THESE TERMS.</b></p>
        <p class="mb-4">We reserve the right, in our sole discretion, to modify these Terms at any time. Changes to these Terms will become effective immediately upon the posting thereof. Please review these Terms often to keep yourself apprised of any changes. Your continued use of the Site following the posting of changes will constitute your acceptance of the revised Terms.</p>

        <p class="mb-1"><b>USE OF THE WEBSITE.</b></p>
        <p class="mb-4">By accessing and using this site, you acknowledge and represent that you are over the age of eighteen (18) and that you are able to form a binding, legal contract as this site is not intended for use by consumers under this specified age. You further acknowledge, represent, and warrant that all information you provide through the site and its forms are accurate and your own. You agree not to use the site for any unlawful or prohibited purposes and in accordance with these Terms. We reserve the right, in our sole and absolute discretion to restrict, in whole or in part, your use of the site at any time, with or without notice for any or no reason. We reserve the right and may, in our sole discretion, report actual or perceived violations of law to law enforcement or appropriate authorities. Lastly, this site is not intended for use outside of the United States and is controlled and operated from the United States and is not intended to subject foreign jurisdiction or foreign laws.</p>

        <p class="mb-1"><b>CONTACT INFORMATION.</b></p>
        <p class="mb-4">For questions and concerns, please contact us here: <EmailForm></EmailForm></p>
    </div>
</template>

<script>
export default {
    name: "TermsText",
    props:{
        modals: Boolean
    },
    data() {
        return {
            app_name: document.querySelector('title').text,
        };
    },
    mounted() {

    }
}
</script>

<style lang="scss" scoped>
    span.modal-link {
        color: #0d6efd!important;
        cursor: pointer;
    }
</style>
