name: Dependabot reviewer

on: workflow_dispatch

permissions:
  pull-requests: write
  contents: write

jobs:
  review-dependabot-pr:
    runs-on: [self-hosted]
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
      - name: Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v2.0.0
        with:
          token: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
      # - name: Enable auto-merge for Dependabot PRs
      #   run: gh pr merge --auto --merge "$PR_URL"
      #   env:
      #     PR_URL: ${{github.event.pull_request.html_url}}
      #     GITHUB_TOKEN: ${{secrets.GLOBAL_GITHUB_TOKEN}}
      # - name: Approve patch and minor updates
      #   if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor'}}
      #   run: gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes a patch or minor update**"
      #   env:
      #     PR_URL: ${{github.event.pull_request.html_url}}
      #     GITHUB_TOKEN: ${{secrets.GLOBAL_GITHUB_TOKEN}}
      # - name: Approve major updates of development dependencies
      #   if: ${{steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major' && steps.dependabot-metadata.outputs.dependency-type == 'direct:development'}}
      #   run: gh pr review $PR_URL --approve -b "I'm **approving** this pull request because **it includes a major update of a dependency**"
      #   env:
      #     PR_URL: ${{github.event.pull_request.html_url}}
      #     GITHUB_TOKEN: ${{secrets.GLOBAL_GITHUB_TOKEN}}
